import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:intl/intl.dart';
import '../../models/rental_listing_model.dart';
import '../../services/rental_listing_service.dart';
import '../../features/bill_reminder/services/cloudinary_service.dart';

// --- THEME COLORS ---
const Color bgDeepNavy = Color(0xFF252A34);
const Color accentTeal = Color(0xFF08D9D6);
const Color lightText = Color(0xFFEAEAEA);
const Color cardBg = Color(0xFF1A1F2E);
const Color inputBg = Color(0xFF2A303C);

class AddRentalListingScreen extends StatefulWidget {
  const AddRentalListingScreen({super.key});

  @override
  State<AddRentalListingScreen> createState() => _AddRentalListingScreenState();
}

class _AddRentalListingScreenState extends State<AddRentalListingScreen> {
  final _formKey = GlobalKey<FormState>();
  final _service = RentalListingService();
  final _auth = FirebaseAuth.instance;
  final _firestore = FirebaseFirestore.instance;

  // Form Fields
  String _type = 'room';
  final TextEditingController _rentController = TextEditingController();
  final TextEditingController _locationController = TextEditingController();
  DateTime _availableFrom = DateTime.now();
  String _furnishingStatus = 'unfurnished';
  int _rooms = 1;
  int _bathrooms = 1;
  bool _attachedBath = false;
  bool _gasAvailable = false;
  bool _parkingAvailable = false;
  final List<XFile> _selectedImages = [];
  final List<String> _uploadedImageUrls = [];
  final TextEditingController _phoneController = TextEditingController();

  String _ownerName = '';
  bool _isLoading = false;
  bool _isUploadingImages = false;

  @override
  void initState() {
    super.initState();
    _loadUserProfile();
  }

  @override
  void dispose() {
    _rentController.dispose();
    _locationController.dispose();
    _phoneController.dispose();
    super.dispose();
  }

  Future<void> _loadUserProfile() async {
    final user = _auth.currentUser;
    if (user != null) {
      try {
        final doc = await _firestore.collection('users').doc(user.uid).get();
        if (doc.exists) {
          final data = doc.data()!;
          setState(() {
            _ownerName = data['fullName'] ?? '';
            _phoneController.text = data['phone'] ?? '';
          });
        }
      } catch (e) {
        debugPrint('Error loading user profile: $e');
      }
    }
  }

  Future<void> _pickImages() async {
    if (_selectedImages.length >= 5) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Maximum 5 images allowed')),
      );
      return;
    }

    final ImagePicker picker = ImagePicker();
    final List<XFile> images = await picker.pickMultiImage();

    if (images.isNotEmpty) {
      setState(() {
        _selectedImages.addAll(images);
        if (_selectedImages.length > 5) {
          _selectedImages.removeRange(5, _selectedImages.length);
        }
      });
    }
  }

  Future<bool> _uploadImages() async {
    setState(() => _isUploadingImages = true);
    _uploadedImageUrls.clear();

    for (var image in _selectedImages) {
      final url = await CloudinaryService.uploadBillImage(image);
      if (url != null) {
        _uploadedImageUrls.add(url);
      }
    }

    setState(() => _isUploadingImages = false);
    return _uploadedImageUrls.isNotEmpty;
  }

  Future<void> _submitForm() async {
    if (!_formKey.currentState!.validate()) return;

    if (_selectedImages.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select at least one image')),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      // 1. Upload images
      final uploadSuccess = await _uploadImages();
      if (!uploadSuccess) {
        throw Exception('Failed to upload images. Please try again.');
      }

      // 2. Create model
      final user = _auth.currentUser;
      final listing = RentalListing(
        listingId: '', // Auto-generated by Firestore
        type: _type,
        rentAmount: int.parse(_rentController.text),
        location: _locationController.text,
        availableFrom: _availableFrom,
        furnishingStatus: _furnishingStatus,
        rooms: _rooms,
        bathrooms: _bathrooms,
        attachedBath: _attachedBath,
        gasAvailable: _gasAvailable,
        parkingAvailable: _parkingAvailable,
        imageUrls: _uploadedImageUrls,
        ownerUid: user?.uid ?? '',
        ownerName: _ownerName,
        ownerPhone: _phoneController.text,
        status: 'available',
        isApproved: true,
        createdAt: DateTime.now(),
      );

      // 3. Save to Firestore
      await _service.addListing(listing);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Listing submitted successfully!'),
            backgroundColor: Colors.green,
          ),
        );
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e'), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: bgDeepNavy,
      appBar: AppBar(
        title: const Text('Add Rental Listing'),
        centerTitle: true,
      ),
      body: _isLoading || _isUploadingImages
          ? Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const CircularProgressIndicator(color: accentTeal),
                  const SizedBox(height: 16),
                  Text(
                    _isUploadingImages
                        ? 'Uploading Images...'
                        : 'Submitting Listing...',
                    style: const TextStyle(color: lightText),
                  ),
                ],
              ),
            )
          : SingleChildScrollView(
              padding: const EdgeInsets.all(20),
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Listing Type
                    _buildLabel('Listing Type'),
                    _buildDropdown(
                      value: _type,
                      items: [
                        {'label': 'Room', 'value': 'room'},
                        {'label': 'Portion', 'value': 'portion'},
                        {'label': 'Full House', 'value': 'full_house'},
                      ],
                      onChanged: (val) => setState(() => _type = val!),
                    ),
                    const SizedBox(height: 20),

                    // Rent Amount
                    _buildLabel('Rent Amount (PKR)'),
                    _buildTextField(
                      controller: _rentController,
                      hint: 'e.g. 15000',
                      keyboardType: TextInputType.number,
                      validator: (val) =>
                          val!.isEmpty ? 'Enter rent amount' : null,
                    ),
                    const SizedBox(height: 20),

                    // Location
                    _buildLabel('Location / Block'),
                    _buildTextField(
                      controller: _locationController,
                      hint: 'e.g. Block A, Street 5, Phase 2',
                      validator: (val) =>
                          val!.isEmpty ? 'Enter location' : null,
                    ),
                    const SizedBox(height: 20),

                    // Available From
                    _buildLabel('Available From'),
                    GestureDetector(
                      onTap: _pickDate,
                      child: Container(
                        padding: const EdgeInsets.all(16),
                        decoration: BoxDecoration(
                          color: inputBg,
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Text(
                              DateFormat('dd MMM, yyyy').format(_availableFrom),
                              style: const TextStyle(color: lightText),
                            ),
                            const Icon(Icons.calendar_today, color: accentTeal),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(height: 20),

                    // Furnishing Status
                    _buildLabel('Furnishing Status'),
                    _buildDropdown(
                      value: _furnishingStatus,
                      items: [
                        {'label': 'Furnished', 'value': 'furnished'},
                        {'label': 'Semi-Furnished', 'value': 'semi'},
                        {'label': 'Unfurnished', 'value': 'unfurnished'},
                      ],
                      onChanged: (val) =>
                          setState(() => _furnishingStatus = val!),
                    ),
                    const SizedBox(height: 20),

                    // Rooms & Bathrooms
                    Row(
                      children: [
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              _buildLabel('Rooms'),
                              _buildStepper(
                                value: _rooms,
                                min: 1,
                                max: 10,
                                onAdd: () => setState(
                                    () => _rooms < 10 ? _rooms++ : null),
                                onRemove: () => setState(
                                    () => _rooms > 1 ? _rooms-- : null),
                              ),
                            ],
                          ),
                        ),
                        const SizedBox(width: 20),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              _buildLabel('Bathrooms'),
                              _buildStepper(
                                value: _bathrooms,
                                min: 1,
                                max: 5,
                                onAdd: () => setState(
                                    () => _bathrooms < 5 ? _bathrooms++ : null),
                                onRemove: () => setState(
                                    () => _bathrooms > 1 ? _bathrooms-- : null),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 20),

                    // Toggles
                    _buildToggle('Attached Bath', _attachedBath,
                        (val) => setState(() => _attachedBath = val)),
                    _buildToggle('Gas Available', _gasAvailable,
                        (val) => setState(() => _gasAvailable = val)),
                    _buildToggle('Parking Available', _parkingAvailable,
                        (val) => setState(() => _parkingAvailable = val)),
                    const SizedBox(height: 20),

                    // Image Picker
                    _buildLabel('Property Images (Min 1, Max 5)'),
                    const SizedBox(height: 10),
                    _buildImagePicker(),
                    const SizedBox(height: 20),

                    // Owner Phone
                    _buildLabel('Owner Phone Number'),
                    _buildTextField(
                      controller: _phoneController,
                      hint: 'e.g. 03001234567',
                      keyboardType: TextInputType.phone,
                      validator: (val) =>
                          val!.isEmpty ? 'Enter phone number' : null,
                    ),
                    const SizedBox(height: 40),

                    // Submit Button
                    SizedBox(
                      width: double.infinity,
                      child: ElevatedButton(
                        style: ElevatedButton.styleFrom(
                          backgroundColor: accentTeal,
                          padding: const EdgeInsets.symmetric(vertical: 16),
                          shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12)),
                        ),
                        onPressed: _submitForm,
                        child: const Text(
                          'Submit Listing',
                          style: TextStyle(
                            color: bgDeepNavy,
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(height: 40),
                  ],
                ),
              ),
            ),
    );
  }

  Widget _buildLabel(String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0, left: 4),
      child: Text(
        text,
        style: const TextStyle(
            color: accentTeal, fontWeight: FontWeight.bold, fontSize: 16),
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String hint,
    TextInputType keyboardType = TextInputType.text,
    String? Function(String?)? validator,
  }) {
    return TextFormField(
      controller: controller,
      keyboardType: keyboardType,
      validator: validator,
      style: const TextStyle(color: lightText),
      decoration: InputDecoration(
        hintText: hint,
        hintStyle: const TextStyle(color: Colors.white24),
        filled: true,
        fillColor: inputBg,
        border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide.none),
        contentPadding:
            const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
      ),
    );
  }

  Widget _buildDropdown({
    required String value,
    required List<Map<String, String>> items,
    required void Function(String?) onChanged,
  }) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16),
      decoration: BoxDecoration(
        color: inputBg,
        borderRadius: BorderRadius.circular(12),
      ),
      child: DropdownButtonHideUnderline(
        child: DropdownButton<String>(
          value: value,
          isExpanded: true,
          dropdownColor: cardBg,
          style: const TextStyle(color: lightText),
          items: items.map((item) {
            return DropdownMenuItem<String>(
              value: item['value'],
              child: Text(item['label']!),
            );
          }).toList(),
          onChanged: onChanged,
        ),
      ),
    );
  }

  Widget _buildStepper({
    required int value,
    required int min,
    required int max,
    required VoidCallback onAdd,
    required VoidCallback onRemove,
  }) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      decoration: BoxDecoration(
        color: inputBg,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          IconButton(
            icon: const Icon(Icons.remove_circle_outline, color: accentTeal),
            onPressed: onRemove,
          ),
          Text(
            value.toString(),
            style: const TextStyle(
                color: lightText, fontSize: 18, fontWeight: FontWeight.bold),
          ),
          IconButton(
            icon: const Icon(Icons.add_circle_outline, color: accentTeal),
            onPressed: onAdd,
          ),
        ],
      ),
    );
  }

  Widget _buildToggle(String label, bool value, void Function(bool) onChanged) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0),
      child: SwitchListTile(
        title: Text(label, style: const TextStyle(color: lightText)),
        value: value,
        activeThumbColor: accentTeal,
        onChanged: onChanged,
        contentPadding: EdgeInsets.zero,
      ),
    );
  }

  Widget _buildImagePicker() {
    return Column(
      children: [
        if (_selectedImages.isNotEmpty)
          SizedBox(
            height: 100,
            child: ListView.builder(
              scrollDirection: Axis.horizontal,
              itemCount: _selectedImages.length,
              itemBuilder: (context, index) {
                return GestureDetector(
                  onTap: () => _showImagePreview(_selectedImages[index].path),
                  child: Stack(
                    children: [
                      Container(
                        margin: const EdgeInsets.only(right: 10),
                        width: 100,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(12),
                          border: Border.all(color: accentTeal),
                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(12),
                          child: Image.file(
                            File(_selectedImages[index].path),
                            fit: BoxFit.cover,
                            errorBuilder: (context, error, stackTrace) {
                              return const Center(
                                  child: Icon(Icons.image, color: Colors.grey));
                            },
                          ),
                        ),
                      ),
                      Positioned(
                        top: 0,
                        right: 10,
                        child: GestureDetector(
                          onTap: () {
                            setState(() => _selectedImages.removeAt(index));
                          },
                          child: Container(
                            decoration: const BoxDecoration(
                                color: Colors.red, shape: BoxShape.circle),
                            child: const Icon(Icons.close,
                                color: Colors.white, size: 20),
                          ),
                        ),
                      ),
                    ],
                  ),
                );
              },
            ),
          ),
        const SizedBox(height: 10),
        ElevatedButton.icon(
          onPressed: _pickImages,
          icon: const Icon(Icons.add_a_photo),
          label: const Text('Pick Images'),
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.white10,
            foregroundColor: accentTeal,
            side: const BorderSide(color: accentTeal),
            shape:
                RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          ),
        ),
      ],
    );
  }

  void _showImagePreview(String imagePath) {
    showDialog(
      context: context,
      builder: (context) => Dialog(
        insetPadding: EdgeInsets.zero,
        backgroundColor: Colors.black,
        child: Stack(
          children: [
            Center(
              child: InteractiveViewer(
                minScale: 1.0,
                maxScale: 4.0,
                child: Image.file(
                  File(imagePath),
                  fit: BoxFit.contain,
                  errorBuilder: (context, error, stackTrace) {
                    return const Center(
                        child: Icon(Icons.broken_image,
                            color: Colors.grey, size: 60));
                  },
                ),
              ),
            ),
            Positioned(
              top: MediaQuery.of(context).padding.top + 16,
              right: 16,
              child: GestureDetector(
                onTap: () => Navigator.pop(context),
                child: Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: Colors.black54,
                    shape: BoxShape.circle,
                    border: Border.all(color: accentTeal, width: 1.5),
                  ),
                  child: const Icon(Icons.close, color: Colors.white, size: 24),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Future<void> _pickDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _availableFrom,
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365)),
      builder: (context, child) => Theme(
        data: ThemeData.dark().copyWith(
          colorScheme: const ColorScheme.dark(
            primary: accentTeal,
            onPrimary: bgDeepNavy,
            surface: cardBg,
          ),
        ),
        child: child!,
      ),
    );
    if (picked != null) {
      setState(() => _availableFrom = picked);
    }
  }
}
